apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaguar-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaguar-apps
  template:
    metadata:
      labels:
        app: jaguar-apps
    spec:
      containers:
      - name: jaguar-apps
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred-i3

